# Site settings
title: Yvonne Hand and Footcare
description: "Professionele hand en voetzorg en medisch pedicure."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.jpg
incremental: true

# Hero
hero:
    hero_img: hero.jpg
    hero_title: Yvonne Hand and Footcare
    hero_description: Professionele hand en voetzorg en medisch pedicure.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +316 34 60 40 32
    email: yvonne.burda@hotmail.com
    address: Burgemeester Pijlsstraat 5b, <br> Schinnen

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Burgemeester Pijlsstraat 5b, Schinnen
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
feed: yes

# Footer
copyright: © 2015 DentistSmile - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
